version: "3.8"

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - sparknet

  spark-job:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-job
    depends_on:
      - minio
    networks:
      - sparknet

volumes:
  minio-data:

networks:
  sparknet:
    driver: bridge